### PR TITLE
Kab locale

### PR DESCRIPTION
**Pull request by belkacem77**
Kabyle locale for GreenShot.

### CODE REVIEW

**Comment by SlimaneAmiri** [comment]
ayuz a gma

**Comment by belkacem77** [comment]
Slimane, we can invite more users tu uses the kab localized version of GreeShot. Th app seems to be the best in sreenshots area

**Comment by Lakritzator** [comment]
Thanks, I merged them in develop and will check if things are working as expected in the release branch for the coming bugfix release.

Can you do me one more favour and translate the Imgur & Flickr plugin translations too?
Those are the ones that are still missing.
https://github.com/greenshot/greenshot/blob/develop/Greenshot.Addon.Imgur/Languages/language_imgurplugin-en-US.xml

https://github.com/greenshot/greenshot/blob/develop/Greenshot.Addon.Flickr/Languages/language_flickrplugin-en-US.xml

**Comment by Lakritzator** [comment]
I added your translations to the coming bugfix release, maybe you want to test this:
https://github.com/greenshot/greenshot/releases/tag/Greenshot-UNSTABLE-1.2.9.125

I actually noticed that a lot of stuff is still in french, I guess you translated from french?
See the settings.

Currently I don't think we can go live with that, if they are not finished.

**Comment by belkacem77** [comment]
Thanks for adding kab locale. Yes translations are made from French files. I will upload an udpate today.

**Comment by belkacem77** [comment]
Last release tested. Kab locale is supported . Thanks for support. I will work now on the html help file and upload it as soon as possible.

**Comment by Lakritzator** [comment]
I thank you for making this possible for all people who speak Taqbaylit.
No hurries with the help, as I release officially tomorrow there won't be anything for the next two weeks (and probably more)

**Comment by SlimaneAmiri** [comment]
Thank you for all.  So we have two weeks to finish the help file?

**Comment by Lakritzator** [comment]
No you have all the time you need 😄 
I just wanted to say that even if you would make it today, the earliest possible rollout would be in over two to three weeks. And it would also depend on if we have anything urgent, otherwise it might take longer.

**Comment by SlimaneAmiri** [comment]
I understand. Thank you mister krom.

Le 28 janv. 2017 23:05, "Robin Krom" <notifications@github.com> a écrit :

No you have all the time you need 😄
I just wanted to say that even if you would make it today, the earliest
possible rollout would be in over two to three weeks. And it would also
depend on if we have anything urgent, otherwise it might take longer.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/greenshot/greenshot/pull/51#issuecomment-275878014>,
or mute
the thread

**Pull request merged**
