### PR TITLE
italian language files update

### PR DESCRIPTION
**Pull request by bovirus**
@Lakritzator 

I made a single PR with all language files update regarding

installer
GUI
website
plugins

Please merge. Thanks.

### CODE REVIEW

**Comment by bovirus** [comment]
@Lakritzator

Could you please merge it? Thanks.

**Comment by Lakritzator** [comment]
You forgot the changes mentioned here: https://github.com/greenshot/greenshot/issues/225#issuecomment-670380660

**Comment by bovirus** [comment]
@Lakritzator 

I left as the last because I was not sure about it.

pelase merge this PR and I will add as soon the other strings.

Thanks.

**Comment by bovirus** [comment]
@Lakritzator 

Thanks.

It seems that translation

     <resource name="WindowCaptureModes.Aero">Usa colori personalizzati</resource>
     <resource name="WindowCaptureModes.AeroTransparent">Mantieni trasparenza</resource>
     <resource name="WindowCaptureModes.Auto">Automaticamente</resource>
     <resource name="WindowCaptureModes.GDI">Usa i colori predefiniti</resource>
     <resource name="WindowCaptureModes.Screen">Come visualizzata</resource>

are already included.

If it's true you can release a new build.

**Comment by Lakritzator** [comment]
https://github.com/greenshot/greenshot/releases/tag/v1.3.120

**Pull request merged**
