### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by a-polivanchuk**
This is update for Ukrainian translations with some corrections.
Ukrainian translation is managed on Crowdin:
https://crowdin.com/project/greenshot-unofficial

### CODE REVIEW

**Comment by a-polivanchuk** [comment]
I have a question about branches.
Is it ok to work on translations in branch /develop?

**Comment by a-polivanchuk** [comment]
@Lacrizator could you please explain why you rejected the pull request?

**Comment by Lakritzator** [comment]
Sorry, I didn't reject it, I deleted a branch and didn't think about the PRs.
I will get back to you on the details, but I think we should move forward to Crowdin :)

**Comment by Lakritzator** [comment]
Besides, a better target would be master, at least currently.

**Comment by a-polivanchuk** [comment]
Ok, I see.
I'll create new PR to Master later, or you can pick my changes here and do it by yourself :)
Thanks!

**Comment by a-polivanchuk** [comment]
@Lakritzator Could you please take a look at this PR? Is it good to be merged?
Thanks!

**Pull request closed without merging**
