### PR TITLE
Add CTRL+Wheel zoom

### PR DESCRIPTION
**Pull request by k41c**

### CODE REVIEW

**Comment by k41c** [comment]
Hi,

I'll looking some time for the zoom feature until I saw that zoom was implemented in 1.3 , thanks for that :). So most of the stuff where done. I just add additional functionality to Zoom in/out with the mouse wheel. Just hit CTRL and start scroling.

Hopefully you found this also helpfull.

Regards K41c

**Comment by Lakritzator** [comment]
Great!!! I still have to try it out, but I understood what it should do and it looks great, so I merged it right away.

**Comment by Lakritzator** [comment]
I finally got time to try it out, VERY NICE!!! Thanks! ❤️

**Comment by Lakritzator** [comment]
I still need to update the readme, I will make the pre-release available later today.

**Comment by mischlrebl** [comment]
@k41c cool work! can i get in contact with you some how?

**Pull request merged**
